### PR TITLE
Jack dev

### PR DESCRIPTION
**Pull request by jalexanderqed**
So I realized I've been working on the master branch of the old repository for a while, and I'd like to merge this in as I've just pushed it. If you want me to keep it in a separate branch for a while until it's more finished, that's fine.

### CODE REVIEW

**Comment by b-huynh** [comment]
Sorry I missed this. It looks like some of these commits have already been pushed. Do you still want me to merge this or should I close it?

**Comment by jalexanderqed** [comment]
At this point, I'm still very actively working on it, so we should probably just put it off until my Master's presentation (hopefully Wednesday).

**Comment by jalexanderqed** [comment]
@b-huynh My master's presentation is Tuesday, and this is ready to be merged. I'll be talking to Tobias about who will work on it in future.

**Comment by b-huynh** [comment]
Done. Good luck on the presentation!

**Pull request merged**
